# Generated by Django 3.0.1 on 2020-01-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casename', models.CharField(max_length=64, verbose_name='用例标题')),
                ('casedesc', models.CharField(max_length=200, verbose_name='用例描述')),
                ('case_type', models.CharField(max_length=100, verbose_name='用例类型')),
                ('case_creater', models.CharField(max_length=200, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('result', models.CharField(max_length=100, verbose_name='执行结果')),
            ],
            options={
                'verbose_name': '用例管理',
                'verbose_name_plural': '用例管理',
                'db_table': 'case',
            },
        ),
    ]
